/* soapXMethodQuotesObject.h
   Generated by gSOAP 2.6.2 from xmethods_quote_service.h
   Copyright (C) 2001-2004 Genivia, Inc. All Rights Reserved.
   This software is released under the gSOAP public license and GPL.
   See README.txt for further details.
*/

#ifndef soapXMethodQuotes_H
#define soapXMethodQuotes_H
#include "soapH.h"
SOAP_BEGIN_NAMESPACE(soap)
class XMethodQuotes : public soap
{    public:
	XMethodQuotes() { soap_init(this); };
	~XMethodQuotes() { soap_destroy(this); soap_end(this); soap_done(this); };
	int serve() { return soap_serve(this); };
};
SOAP_END_NAMESPACE(soap)
#endif
