/* soapClientLib.c
   Generated by gSOAP 2.6.2 from xmethods_quote_service.h
   Copyright (C) 2001-2004 Genivia, Inc. All Rights Reserved.
   This software is released under the gSOAP public license and GPL.
   See README.txt for further details.
*/
#define WITH_NOGLOBAL
#define SOAP_FMAC3 static
#include "soapC.c"
#include "soapClient.c"

/* end of soapClientLib.c */
