/* soapClient.c
   Generated by gSOAP 2.6.2 from xmethods_quote_service.h
   Copyright (C) 2001-2004 Genivia, Inc. All Rights Reserved.
   This software is released under the gSOAP public license and GPL.
   See README.txt for further details.
*/
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_BEGIN_NAMESPACE(soap)

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.6.2 2004-07-04 14:40:10 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getQuote(struct soap *soap, const char *URL, const char *action, char *_symbol, struct ns1__getQuoteResponse *param_1)
{
	struct ns1__getQuote soap_tmp_ns1__getQuote;
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!URL)
		URL = "http://64.124.140.30:9090/soap";
	if (!action)
		action = "urn:xmethods-delayed-quotes#getQuote";
	soap_tmp_ns1__getQuote._symbol=_symbol;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__getQuote(soap, &soap_tmp_ns1__getQuote);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_ns1__getQuote(soap, &soap_tmp_ns1__getQuote, "ns1:getQuote", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	}
	if (soap_connect(soap, URL, action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getQuote(soap, &soap_tmp_ns1__getQuote, "ns1:getQuote", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
#ifndef WITH_LEANER
	 || soap_putattachments(soap)
#endif
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_ns1__getQuoteResponse(soap, param_1);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__getQuoteResponse(soap, param_1, "ns1:getQuoteResponse", "ns1:getQuoteResponse");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_getattachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_END_NAMESPACE(soap)

#ifdef __cplusplus
}
#endif

/* end of soapClient.c */
