/* soapXMethodQuotesProxy.h
   Generated by gSOAP 2.6.2 from xmethods_quote_service.h
   Copyright (C) 2001-2004 Genivia, Inc. All Rights Reserved.
   This software is released under the gSOAP public license and GPL.
   See README.txt for further details.
*/

#ifndef soapXMethodQuotes_H
#define soapXMethodQuotes_H
#include "soapH.h"
SOAP_BEGIN_NAMESPACE(soap)
class XMethodQuotes
{   public:
  struct soap *soap;
  const char *endpoint;
  XMethodQuotes() { soap = soap_new(); endpoint = "http://64.124.140.30:9090/soap"; };
  virtual ~XMethodQuotes() { if (soap) { soap_destroy(soap); soap_end(soap); soap_done(soap); SOAP_FREE((void*)soap); } };
  virtual int ns1__getQuote(char *_symbol, struct ns1__getQuoteResponse *param_1) { return soap ? soap_call_ns1__getQuote(soap, endpoint, NULL, _symbol, param_1) : SOAP_EOM; };
};
SOAP_END_NAMESPACE(soap)
#endif
