/* soapStub.h
   Generated by gSOAP 2.6.2 from xmethods_quote_service.h
   Copyright (C) 2001-2004 Genivia, Inc. All Rights Reserved.
   This software is released under the gSOAP public license and GPL.
   See README.txt for further details.
*/
#ifndef soapStub_H
#define soapStub_H
#include "../stdsoap2.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_BEGIN_NAMESPACE(soap)

/* Enumerations */

/* Classes and Structs */

/* ns1:getQuoteResponse: */
struct ns1__getQuoteResponse
{
  float _Result;  /* return */
};

/* ns1:getQuote: */
struct ns1__getQuote
{
  char *_symbol;
};

/* SOAP Header: */
struct SOAP_ENV__Header
{
  void *dummy;  /* transient */
};

/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
  char *SOAP_ENV__Value;
  char *SOAP_ENV__Node;
  char *SOAP_ENV__Role;
};

/* SOAP-ENV:Detail: */
struct SOAP_ENV__Detail
{
  int __type; /* any type of element <value> */
  void *value;  /* transient */
  char *__any;
};

/* SOAP Fault: */
struct SOAP_ENV__Fault
{
  char *faultcode;
  char *faultstring;
  char *faultactor;
  struct SOAP_ENV__Detail *detail;
  struct SOAP_ENV__Code *SOAP_ENV__Code;
  char *SOAP_ENV__Reason;
  struct SOAP_ENV__Detail *SOAP_ENV__Detail;
};

/* Types With Custom (De)serializers: */

/* Typedefs */
typedef char *_XML;
typedef char *_QName;

/* Extern */

/* Remote Methods */

SOAP_FMAC5 int SOAP_FMAC6 ns1__getQuote(struct soap*, char *, struct ns1__getQuoteResponse *);

/* Stubs */

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getQuote(struct soap*, const char*, const char*, char *, struct ns1__getQuoteResponse *);

/* Skeletons */

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__getQuote(struct soap*);

SOAP_END_NAMESPACE(soap)

#ifdef __cplusplus
}
#endif

#endif

/* end of soapStub.h */
