
find_path(CPPUNIT_INCLUDE_DIR
    TestSuite.h PATH_SUFFIXES cppunit )

find_library(CPPUNIT_LIBRARY
    NAMES cppunit-1.12 cppunit )

if (CPPUNIT_INCLUDE_DIR AND CPPUNIT_LIBRARY)
    set(CPPUNIT_FOUND on)
endif (CPPUNIT_INCLUDE_DIR AND CPPUNIT_LIBRARY)
